from .categories import CategoryProduct
from .brands import BrandProduct
from .products import Product, PhotoProduct

from .specifications.computer_case_specifications import ComputerCaseSpecifications
from .specifications.cooler_specifications import CoolerSpecifications
from .specifications.hdd_specifications import HDDSpecifications
from .specifications.motherboard_specifications import MotherboardSpecifications
from .specifications.power_supply_specifications import PowerSupplySpecifications
from .specifications.processor_specifications import ProcessorSpecifications
from .specifications.ram_specifications import RamSpecifications
from .specifications.solid_state_drive_specifications import SolidStateDriveSpecifications
from .specifications.videocart_specifications import VideoCartSpecifications

