# Generated by Django 4.1 on 2022-08-19 11:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'Пользователь с таким логином, уже существует'}, help_text='Логин может иметь максимум 50 символов и содержать только буквы и цифры.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9]*', code='invalid_username', message='Введенный логин должен состоять только из латинских букв и цифр')], verbose_name='Логин пользователя')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email пользователя')),
                ('first_name', models.CharField(help_text='Имя пользователя может иметь максимум 50 символов и содержать только буквы', max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Zа-яА-я]*', code='invalid_first_name', message='Имя пользователя может содержать только буквы')], verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия пользователя может иметь максимум 50 символов и содержать только буквы', max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Zа-яА-я]*', code='invalid_last_name', message='Фамилия пользователя может содержать только буквы')], verbose_name='Фамилия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
