# Generated by Django 4.1 on 2022-09-13 10:46

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Имя пользователя может иметь максимум 50 символов и содержать только русские буквы', max_length=50, validators=[accounts.validators.validation_first_last_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Фамилия пользователя может иметь максимум 50 символов и содержать только русские буквы', max_length=50, validators=[accounts.validators.validation_first_last_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Пользователь с таким логином, уже существует'}, help_text='Логин может иметь максимум 50 символов и содержать только буквы и цифры.', max_length=50, unique=True, validators=[accounts.validators.validation_username], verbose_name='Логин пользователя'),
        ),
    ]
