# Generated by Django 4.1 on 2022-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_alter_categoryproduct_photo_and_more'),
        ('accounts', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_brands',
            field=models.ManyToManyField(to='shop_products.brandproduct', verbose_name='Любимые производители (бренды)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(to='shop_products.product', verbose_name='Любимые товары'),
        ),
    ]
