# Generated by Django 4.1 on 2023-02-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_favorite_brands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mail_confirmation',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
    ]
