# Generated by Django 4.1 on 2022-09-26 19:51

from django.db import migrations, models
import shop_products.models.categories
import shop_products.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='photo',
            field=models.ImageField(help_text='Картинка, которая отображается на главном экране, при выборе категории', upload_to=shop_products.models.categories.upload_to, verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='factorydataramspecifications',
            name='warranty',
            field=models.IntegerField(verbose_name='Гарантия от производителя'),
        ),
        migrations.AlterField(
            model_name='photoproduct',
            name='photo',
            field=models.ImageField(upload_to=shop_products.models.products.upload_to, verbose_name='Фотографии товара'),
        ),
    ]
