# Generated by Django 4.1 on 2022-09-13 11:41

from django.db import migrations, models
import shop_products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(choices=[('Корпус', 'Computer Case'), ('Кулер', 'Cooler'), ('Жесткий диск (HDD)', 'Hdd'), ('Блок питания', 'Power Supply'), ('Процессор', 'Processor'), ('Оперативная память (RAM)', 'Ram'), ('ССД', 'Ssd'), ('Видеокарта', 'Video Cart')], db_index=True, help_text='Название категории товара', max_length=100, unique=True, validators=[shop_products.validators.validate_category_name], verbose_name='Категория'),
        ),
    ]
