# Generated by Django 4.1 on 2022-09-13 13:59

from django.db import migrations, models
import shop_products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_alter_categoryproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(db_index=True, help_text='Название категории товара', max_length=100, unique=True, validators=[shop_products.validators.validate_category_name], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='photo',
            field=models.ImageField(help_text='Картинка, которая отображается на главном экране, при выборе категории', upload_to='test/', verbose_name='Фото категории'),
        ),
    ]
