# Generated by Django 4.1 on 2022-10-11 13:09

from django.db import migrations, models
import phonenumber_field.modelfields
import shop_products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_alter_categoryproduct_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[shop_products.validators.validate_category_name], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Данные с формы "Связаться с нами"',
                'verbose_name_plural': 'Данные с формы "Связаться с нами"',
            },
        ),
    ]
