# Generated by Django 4.1 on 2023-01-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_products', '0003_contactformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_purchase', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время покупки')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество купленного товара')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='Купленные товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'История покупок',
                'ordering': ['user', 'datetime_purchase'],
                'unique_together': {('user', 'products', 'datetime_purchase')},
            },
        ),
    ]
