# Generated by Django 4.1 on 2023-01-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_products', '0004_purchasehistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProductReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('f_delete', models.BooleanField(default=False, verbose_name='Флаг удаления комментрия админом')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения комментария')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], verbose_name='Оценка товара')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_products.commentproductreviewmodel', verbose_name='Отзыв')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, который оставляет отзыв')),
            ],
        ),
    ]
